anythings.comm.rabbitmq.name: anyrabbitmq
anythings.comm.rabbitmq.version: 1.0.0.0
anythings.comm.rabbitmq.built.at: 2022-02-26 16:00:00
anythings.comm.rabbitmq.projectName: anythings-comm-rabbitmq
anythings.comm.rabbitmq.description: Anythings Communication RabbitMQ
anythings.comm.rabbitmq.parentModule: elings-rabbitmq
anythings.comm.rabbitmq.basePackage: xyz.anythings.comm.rabbitmq
anythings.comm.rabbitmq.scanEntityPackage: xyz.anythings.comm.rabbitmq.entity
anythings.comm.rabbitmq.scanServicePackage: xyz.anythings.comm.rabbitmq.rest
