operato.gw.mqbase.name: gw-mqbase
operato.gw.mqbase.version: 1.0.0.0
operato.gw.mqbase.built.at: 2022-02-26 16:00:00
operato.gw.mqbase.projectName: operato-gw-mqbase
operato.gw.mqbase.description: Operato Gateway MQ Base
operato.gw.mqbase.parentModule: logis
operato.gw.mqbase.basePackage: operato.gw.mqbase
operato.gw.mqbase.scanEntityPackage: operato.gw.mqbase.entity
operato.gw.mqbase.scanServicePackage: operato.gw.mqbase.rest
operato.gw.mqbase.rabbitQueue: gw-mqbase