SELECT
	COALESCE(MIN(JOB.INPUT_SEQ), -1) AS INPUT_SEQ
FROM
	JOB_INSTANCES JOB INNER JOIN CELLS CELL ON JOB.DOMAIN_ID = CELL.DOMAIN_ID AND JOB.SUB_EQUIP_CD = CELL.CELL_CD
WHERE
	JOB.DOMAIN_ID = :domainId
	AND JOB.BATCH_ID = :batchId
	AND JOB.INPUT_SEQ > :inputSeq
	AND JOB.STATUS in (:statuses)
	AND CELL.EQUIP_CD = :equipCd
	AND CELL.STATION_CD = :stationCd
