SELECT
	A.SUB_EQUIP_CD, A.CLASS_CD, B.PICK_QTY, A.PICKED_QTY
FROM
	(SELECT
		J.SUB_EQUIP_CD,
		J.CLASS_CD,
		SUM(J.PICKED_QTY) AS PICKED_QTY
	FROM
		JOB_INSTANCES J INNER JOIN CELLS C ON J.DOMAIN_ID = C.DOMAIN_ID AND J.EQUIP_CD = C.EQUIP_CD AND J.SUB_EQUIP_CD = C.CELL_CD
	WHERE
		J.DOMAIN_ID = :domainId
		AND J.BATCH_ID = :batchId
		AND J.COM_CD = :comCd
		AND J.SKU_CD = :skuCd
		AND C.ACTIVE_FLAG = true
		#if($stationCd)
		AND C.STATION_CD = :stationCd
		#end
		AND J.PICKED_QTY > 0
	GROUP BY
		J.SUB_EQUIP_CD, J.CLASS_CD) A
	
	INNER JOIN
	
	(SELECT
		J.SUB_EQUIP_CD,
		J.CLASS_CD,
		SUM(J.PICK_QTY) AS PICK_QTY
	FROM
		JOB_INSTANCES J INNER JOIN CELLS C ON J.DOMAIN_ID = C.DOMAIN_ID AND J.EQUIP_CD = C.EQUIP_CD AND J.SUB_EQUIP_CD = C.CELL_CD
	WHERE
		J.DOMAIN_ID = :domainId
		AND J.BATCH_ID = :batchId
		AND J.COM_CD = :comCd
		AND J.SKU_CD = :skuCd
		AND C.ACTIVE_FLAG = true
		#if($stationCd)
		AND C.STATION_CD = :stationCd
		#end
	GROUP BY
		J.SUB_EQUIP_CD, J.CLASS_CD) B
	
	ON A.SUB_EQUIP_CD = B.SUB_EQUIP_CD

ORDER BY
	A.SUB_EQUIP_CD, A.CLASS_CD