SELECT
	*
FROM
	(SELECT
		ROW_NUMBER() OVER (ORDER BY X.DIFF_QTY ASC, X.INPUT_QTY ASC, X.PLAN_QTY ASC, X.RESULT_QTY ASC, X.SKU_CD DESC) AS INPUT_SEQ,
		X.*
	FROM
		(SELECT
			A.COM_CD, A.SKU_CD, A.SKU_NM, A.RESULT_QTY
			, B.INPUT_QTY, B.PLAN_QTY
			, (B.PLAN_QTY - A.RESULT_QTY) AS DIFF_QTY
		FROM
			(SELECT
				J.COM_CD,
				J.SKU_CD,
				MIN(J.SKU_NM) AS SKU_NM,
				SUM(J.PICKED_QTY) AS RESULT_QTY
			FROM
				JOB_INSTANCES J INNER JOIN CELLS C ON J.DOMAIN_ID = C.DOMAIN_ID AND J.EQUIP_CD = C.EQUIP_CD AND J.SUB_EQUIP_CD = C.CELL_CD
			WHERE
				J.DOMAIN_ID = :domainId
				AND J.BATCH_ID = :batchId
				AND C.ACTIVE_FLAG = true
				#if($stationCd)
				AND C.STATION_CD = :stationCd
				#end
				#if($inputOnly)
				AND J.PICKED_QTY > 0
				#end
			GROUP BY
				J.COM_CD, J.SKU_CD) A
				
			INNER JOIN
			
			(SELECT
				J.COM_CD,
				J.SKU_CD,
				COUNT(DISTINCT(J.CLASS_CD)) AS INPUT_QTY,
				SUM(J.PICK_QTY) AS PLAN_QTY
			FROM
				JOB_INSTANCES J INNER JOIN CELLS C ON J.DOMAIN_ID = C.DOMAIN_ID AND J.EQUIP_CD = C.EQUIP_CD AND J.SUB_EQUIP_CD = C.CELL_CD
			WHERE
				J.DOMAIN_ID = :domainId
				AND J.BATCH_ID = :batchId
				AND C.ACTIVE_FLAG = true
				#if($stationCd)
				AND C.STATION_CD = :stationCd
				#end
			GROUP BY
				J.COM_CD, J.SKU_CD
			) B
			
			ON A.COM_CD = B.COM_CD AND A.SKU_CD = B.SKU_CD
	) X
	#if($notInputOnly)
	WHERE
		X.DIFF_QTY > 0
	#end
) Y
ORDER BY
	Y.INPUT_SEQ DESC