SELECT
	DISTINCT JOB.DOMAIN_ID, JOB.STAGE_CD, CELL.IND_CD, CELL.CELL_CD, ROUTER.GW_NM AS GW_PATH
FROM
	JOB_INSTANCES JOB
	INNER JOIN CELLS CELL ON JOB.DOMAIN_ID = CELL.DOMAIN_ID AND JOB.EQUIP_TYPE = CELL.EQUIP_TYPE AND JOB.EQUIP_CD = CELL.EQUIP_CD AND JOB.SUB_EQUIP_CD = CELL.CELL_CD
	LEFT OUTER JOIN INDICATORS IND ON CELL.DOMAIN_ID = IND.DOMAIN_ID AND CELL.IND_CD = IND.IND_CD
	LEFT OUTER JOIN GATEWAYS ROUTER ON IND.DOMAIN_ID = ROUTER.DOMAIN_ID AND IND.GW_CD = ROUTER.GW_CD
WHERE
	JOB.DOMAIN_ID = :domainId
	#if($batchId)
	AND JOB.BATCH_ID = :batchId
	#end
	#if($status)
	AND JOB.STATUS = :status
	#end
	#if($statuses)
	AND JOB.STATUS IN (:statuses)
	#end
	#if($stationCd)
	AND CELL.STATION_CD = :stationCd
	#end