SELECT
	S.ID, S.COM_CD, S.SKU_CD, S.SKU_NM, COALESCE(S.SKU_BARCD, ' ') AS SKU_BARCD, COALESCE(S.BOX_BARCD, ' ') AS BOX_BARCD, S.BOX_IN_QTY, S.SKU_WT, S.BARCD_TYPE
FROM
	SKU S INNER JOIN
	(
		SELECT 
			DISTINCT DOMAIN_ID, COM_CD, CELL_ASSGN_CD AS SKU_CD 
		FROM 
			ORDER_PREPROCESSES 
		WHERE 
			DOMAIN_ID = :domainId
			AND EQUIP_CD IS NOT NULL
			AND BATCH_ID IN (SELECT ID FROM JOB_BATCHES WHERE DOMAIN_ID = :domainId AND BATCH_GROUP_ID = :batchGroupId AND STATUS IN ('WAIT', 'READY', 'RUN')) 
	) J
	ON S.DOMAIN_ID = J.DOMAIN_ID AND S.COM_CD = J.COM_CD AND S.SKU_CD = J.SKU_CD
WHERE
	S.DOMAIN_ID = :domainId
	AND (S.SKU_CD = :skuCd OR S.SKU_BARCD = :skuCd OR S.SKU_BARCD2 = :skuCd OR S.SKU_BARCD3 = :skuCd OR S.BOX_BARCD = :skuCd)