SELECT
	CASE WHEN A.RUN_MIN = 0 THEN 0 ELSE ROUND(A.RESULT_PCS * (60.0 / A.RUN_MIN), 1) END AS UPH,
	A.RUN_MIN AS EQUIP_RUNTIME
FROM (
	SELECT
		Z.RESULT_PCS,
		ROUND(extract(epoch from (PICK_ENDED_AT - PICK_STARTED_AT) / 3600)::integer, 1) AS RUN_HOUR,
		ROUND(extract(epoch from (PICK_ENDED_AT - PICK_STARTED_AT) / 60)::integer, 1) AS RUN_MIN
	FROM (
		SELECT
			J.BATCH_ID,
			COALESCE(B.RESULT_PCS, 0) AS RESULT_PCS,
			COALESCE(TO_TIMESTAMP(MIN(J.PICK_STARTED_AT), 'YYYY-MM-DD HH24:MI:SS'), B.INSTRUCTED_AT)  AS PICK_STARTED_AT,
			COALESCE(TO_TIMESTAMP(MAX(J.PICK_ENDED_AT), 'YYYY-MM-DD HH24:MI:SS'), now()) AS PICK_ENDED_AT
		FROM
			JOB_BATCHES B
			INNER JOIN
			JOB_INSTANCES J ON B.DOMAIN_ID = J.DOMAIN_ID AND B.ID = J.BATCH_ID
		WHERE
			J.DOMAIN_ID = :domainId
			AND J.BATCH_ID = :batchId
		GROUP BY
			J.BATCH_ID, B.RESULT_PCS, B.INSTRUCTED_AT
	) Z
) A