SELECT
	A.*
FROM (
	SELECT
		SKU_CD, SKU_BARCD, SKU_NM, COUNT(DISTINCT CLASS_CD) AS SKU_QTY, SUM(PICK_QTY) AS PLAN_QTY
	FROM
		JOB_INSTANCES
	WHERE
		DOMAIN_ID = :domainId
		AND BATCH_ID = :batchId
		AND (INPUT_SEQ IS NULL OR INPUT_SEQ = 0)
		#if($stationCd)
		AND SUB_EQUIP_CD IN (SELECT CELL_CD FROM CELLS WHERE DOMAIN_ID = :domainId AND EQUIP_CD = :equipCd AND STATION_CD = :stationCd)
		#end
	GROUP BY
		SKU_CD, SKU_BARCD, SKU_NM
) A
ORDER BY
	A.SKU_QTY DESC, A.PLAN_QTY DESC