SELECT
	ID, DOMAIN_ID, :boxPackId AS BOX_PACK_ID, ORDER_NO, ORDER_LINE_NO, ORDER_DETAIL_ID, COM_CD, CLASS_CD, SHOP_CD, SKU_CD, SKU_NM, PACK_TYPE, ORDER_QTY, (PICKED_QTY - COALESCE(BOXED_QTY, 0)) AS PICKED_QTY, COALESCE(BOXED_QTY, 0) AS BOXED_QTY
FROM
	ORDERS
WHERE
	DOMAIN_ID = :domainId AND BATCH_ID = :batchId AND COM_CD = :comCd AND CLASS_CD = :classCd AND PICKED_QTY > 0 AND (BOXED_QTY IS NULL OR PICKED_QTY > BOXED_QTY)
ORDER BY
	ORDER_NO ASC, ORDER_LINE_NO ASC, SKU_CD ASC, ORDER_QTY DESC