SELECT
	DISTINCT(CELL.STATION_CD) AS STATION_CD
FROM
	JOB_INSTANCES JOB INNER JOIN CELLS CELL ON JOB.DOMAIN_ID = CELL.DOMAIN_ID AND JOB.SUB_EQUIP_CD = CELL.CELL_CD
WHERE
    JOB.DOMAIN_ID = :domainId
    AND JOB.BATCH_ID = :batchId
    AND (JOB.INPUT_SEQ IS NOT NULL AND JOB.INPUT_SEQ > 0 AND JOB.INPUT_SEQ < :inputSeq)
    AND CELL.STATION_CD IN (:stationList)
	AND JOB.STATUS = :status