SELECT
	DISTINCT
	X.DOMAIN_ID
	, X.BATCH_ID
	, X.JOB_TYPE
	, X.EQUIP_TYPE
	, X.EQUIP_CD
	, Y.STATION_CD
	, Y.STATION_SEQ
	, X.ORDER_NO
	, X.CLASS_CD
	, X.INPUT_QTY
	, :comCd AS COM_CD
	, :inputSeq AS INPUT_SEQ
	, :boxType AS BOX_TYPE
	, :boxId AS BOX_ID
	, :colorCd AS COLOR_CD
	, :inputType AS INPUT_TYPE
	, :status AS STATUS
FROM (
	SELECT
		J.DOMAIN_ID
		, J.JOB_TYPE
		, J.BATCH_ID
		, J.EQUIP_TYPE
		, J.EQUIP_CD
		, C.STATION_CD
		, J.ORDER_NO
		, J.CLASS_CD
		, SUM(J.PICK_QTY) AS INPUT_QTY
	FROM
		JOB_INSTANCES J INNER JOIN CELLS C 
		ON J.DOMAIN_ID = C.DOMAIN_ID AND J.EQUIP_CD = C.EQUIP_CD AND J.SUB_EQUIP_CD = C.CELL_CD
	WHERE
		J.DOMAIN_ID = :domainId
		AND J.BATCH_ID = :batchId
		AND J.EQUIP_TYPE = :equipType
		AND J.CLASS_CD = :classCd
	GROUP BY
		J.DOMAIN_ID, J.JOB_TYPE, J.BATCH_ID, J.EQUIP_TYPE, J.EQUIP_CD, C.STATION_CD, J.ORDER_NO, J.CLASS_CD
) X
, (SELECT 
		C.DOMAIN_ID
		, C.EQUIP_TYPE
		, C.EQUIP_CD
		, C.STATION_CD
   		, S.STATION_SEQ
	FROM
		CELLS C LEFT OUTER JOIN STATIONS S ON C.DOMAIN_ID = S.DOMAIN_ID AND C.STATION_CD = S.STATION_CD
	WHERE
		C.DOMAIN_ID = :domainId
		AND C.EQUIP_TYPE = :equipType
		AND C.ACTIVE_FLAG = true
) Y
WHERE 
	X.DOMAIN_ID = Y.DOMAIN_ID
	AND X.EQUIP_TYPE = Y.EQUIP_TYPE
	AND X.EQUIP_CD = Y.EQUIP_CD
	AND X.STATION_CD = Y.STATION_CD
ORDER BY 
	Y.STATION_SEQ