UPDATE
	JOB_BATCHES Y
SET
	INSTRUCTED_AT = COALESCE(INSTRUCTED_AT , now())
	, (BATCH_ORDER_QTY, BATCH_SKU_QTY, BATCH_PCS) = (
		SELECT
			COUNT(DISTINCT CLASS_CD), COUNT(DISTINCT SKU_CD), SUM(ORDER_QTY)
		FROM
			ORDERS X
		WHERE
			X.DOMAIN_ID = :domainId
			AND X.BATCH_ID = :batchId
	)
WHERE
	DOMAIN_ID = :domainId
	AND ID = :batchId