SELECT
	OP.SUB_EQUIP_CD AS CHUTE_NO
	, OP.CELL_ASSGN_CD AS SHOP_CD 
	, SHOP.SHOP_NM AS SHOP_NM
	, SUM(OP.TOTAL_PCS) AS ASSIGNED_PCS
FROM
	ORDER_PREPROCESSES OP
LEFT OUTER JOIN
	SHOPS SHOP
ON
	OP.CELL_ASSGN_CD = SHOP.SHOP_CD
WHERE
      OP.DOMAIN_ID = :domainId
AND   OP.BATCH_ID  = :batchId
GROUP BY
	OP.SUB_EQUIP_CD
	, OP.CELL_ASSGN_CD
	, SHOP.SHOP_NM
ORDER BY 
	CHUTE_NO