SELECT
	DISTINCT CELL.CELL_CD, JOB.IND_CD
FROM
	WORK_CELLS CELL INNER JOIN JOB_INSTANCES JOB
  	ON CELL.DOMAIN_ID = JOB.DOMAIN_ID AND CELL.BATCH_ID = JOB.BATCH_ID AND CELL.CELL_CD = JOB.CELL_CD
WHERE
	CELL.DOMAIN_ID = :domainId
   AND CELL.BATCH_ID = :batchId
   AND CELL.STATUS IN (:cellStatuses)
   AND JOB.STATUS IN (:jobStatuses)
