SELECT
	(SELECT COUNT(DISTINCT(SKU_CD)) FROM ORDERS WHERE DOMAIN_ID = :domainId AND BATCH_ID = :batchId AND CLASS_CD IN (SELECT DISTINCT(CELL_ASSGN_CD) FROM ORDER_PREPROCESSES WHERE DOMAIN_ID = :domainId AND BATCH_ID = :batchId AND EQUIP_CD IS NOT NULL AND SUB_EQUIP_CD IS NOT NULL)) AS SKU_CNT,
	A.ORDER_CNT,
	A.TOTAL_PCS
FROM (
   SELECT
      	SUM(TOTAL_PCS) AS TOTAL_PCS,
        COUNT(DISTINCT(CELL_ASSGN_CD)) AS ORDER_CNT
    FROM 
      ORDER_PREPROCESSES
    WHERE 
      DOMAIN_ID = :domainId AND BATCH_ID = :batchId AND EQUIP_CD IS NOT NULL AND SUB_EQUIP_CD IS NOT NULL
) A