UPDATE 
	ORDERS
SET 
	ORDER_TYPE = :orderType, STATUS = 'T'
WHERE 
	DOMAIN_ID = :domainId
	AND BATCH_ID = :batchId
	AND CLASS_CD IN (
		SELECT
			B.CLASS_CD
		FROM (
			SELECT
				A.CLASS_CD, COUNT(1) AS ORDER_TYPE_COUNT
			FROM (
				SELECT CLASS_CD, COM_CD, SKU_CD
				FROM ORDERS
				WHERE DOMAIN_ID = :domainId AND BATCH_ID = :batchId
			) A
			GROUP BY
				A.CLASS_CD, A.COM_CD, A.SKU_CD
		) B
		WHERE
			B.ORDER_TYPE_COUNT > 1
	)