SELECT    
	A.RACK_CD,
	A.RACK_NM,
	A.TOTAL_CELLS - NVL(B.ASSIGNED_CELLS, 0) AS REMAIN_CELLS,
	NVL(B.ASSIGNED_CELLS, 0) AS ASSIGNED_CELLS,
	NVL(B.ASSIGNED_PCS, 0)   AS ASSIGNED_PCS
FROM (
	SELECT 
		REG.RACK_CD,
		REG.RACK_NM,
		COUNT(LOC.EQUIP_CD) AS TOTAL_CELLS
	FROM     
		CELLS LOC INNER JOIN RACKS REG ON LOC.DOMAIN_ID = REG.DOMAIN_ID AND LOC.EQUIP_CD = REG.RACK_CD
	WHERE
		LOC.DOMAIN_ID = :domainId
		AND REG.STAGE_CD = :stageCd
		AND REG.BATCH_ID IS NULL
		AND LOC.ACTIVE_FLAG = :activeFlag
		#if($equipCds)
		AND REG.RACK_CD IN (:equipCds)  
		#end
	GROUP BY 
		REG.RACK_CD, REG.RACK_NM
	) A

	LEFT OUTER JOIN
        
	(SELECT
		EQUIP_CD,
		COUNT(DISTINCT(CELL_ASSGN_CD)) 	AS ASSIGNED_CELLS,
		SUM(TOTAL_PCS)          		AS ASSIGNED_PCS
	FROM
		ORDER_PREPROCESSES
	WHERE
		DOMAIN_ID = :domainId
		AND BATCH_ID = :batchId
	GROUP BY
		EQUIP_CD) B

	ON A.RACK_CD = B.EQUIP_CD

ORDER BY A.RACK_CD