SELECT
	*
FROM
	BOX_PACKS
WHERE
	DOMAIN_ID = :domainId
	AND BATCH_ID = :batchId
	AND SUB_EQUIP_CD = :subEquipCd
	AND BOX_SEQ = (SELECT MAX(BOX_SEQ) FROM BOX_PACKS WHERE DOMAIN_ID = :domainId AND BATCH_ID = :batchId AND SUB_EQUIP_CD = :subEquipCd)