SELECT
	BATCH_ORDER_QTY,
	BATCH_SKU_QTY,
	BATCH_PCS,
	RESULT_ORDER_QTY,
	RESULT_BOX_QTY,
	RESULT_SKU_QTY,
	RESULT_PCS,
	ROUND(RESULT_BOX_QTY * 100.0 / BATCH_ORDER_QTY, 1) AS PROGRESS_RATE
FROM (
	SELECT
		A.BATCH_ORDER_QTY,
		A.BATCH_SKU_QTY,
		A.BATCH_PCS,
		B.RESULT_PCS,
		C.RESULT_SKU_QTY
	FROM (
		(SELECT
			ID AS BATCH_ID,
			BATCH_ORDER_QTY,
			BATCH_SKU_QTY,
			BATCH_PCS
		FROM
			JOB_BATCHES
		WHERE
			DOMAIN_ID = :domainId
			AND ID = :batchId) A
		
		INNER JOIN
		
		(SELECT
			BATCH_ID,
			COALESCE(SUM(PICKED_QTY), 0) AS RESULT_PCS
		FROM
			JOB_INSTANCES
		WHERE
			DOMAIN_ID = :domainId
			AND BATCH_ID = :batchId
			AND PICKED_QTY > 0
		GROUP BY
			BATCH_ID) B
			
		ON A.BATCH_ID = B.BATCH_ID
		
		INNER JOIN
		
		(SELECT
			BATCH_ID,
			COUNT(DISTINCT(SKU_CD)) AS RESULT_SKU_QTY
		FROM (
			SELECT
				BATCH_ID,
				COM_CD,
				SKU_CD,
				COALESCE(SUM(PICK_QTY), 0) AS PLAN_SKU_QTY,
				COALESCE(SUM(PICKED_QTY), 0) AS RESULT_SKU_QTY
			FROM
				JOB_INSTANCES
			WHERE
				DOMAIN_ID = :domainId
				AND BATCH_ID = :batchId
			GROUP BY
				BATCH_ID, COM_CD, SKU_CD
			) Z
		WHERE
			Z.PLAN_SKU_QTY = Z.RESULT_SKU_QTY
		) C

		ON A.BATCH_ID = C.BATCH_ID
		
		LEFT OUTER JOIN
		
		(SELECT
			BATCH_ID,
			COALESCE(COUNT(DISTINCT (CLASS_CD)), 0) AS RESULT_ORDER_QTY,
			COALESCE(COUNT(DISTINCT (BOX_ID)), 0) AS RESULT_BOX_QTY
		FROM
			BOX_PACKS
		WHERE
			DOMAIN_ID = :domainId
			AND BATCH_ID = :batchId
			AND STATUS NOT IN ('A', 'W')
		GROUP BY
			BATCH_ID) D
		
		ON A.BATCH_ID = D.BATCH_ID
	)
) X