INSERT INTO JOB_INSTANCES (
	ID
	, BATCH_ID
	, JOB_DATE
	, JOB_SEQ
	, JOB_TYPE
	, STAGE_CD
	, COM_CD
	, EQUIP_GROUP_CD
	, EQUIP_TYPE
	, EQUIP_CD
	, SHOP_CD
	, SHOP_NM
	, ORDERER_ID
	, ORDERER_NM
	, CLASS_CD
	, SKU_CD
	, SKU_NM
	, SKU_BARCD
	, BOX_IN_QTY
	, INPUT_SEQ
	, BOX_TYPE_CD
	, CUST_ORDER_NO
	, ORDER_NO
	, INVOICE_ID
	, PICK_QTY
	, PICKING_QTY
	, PICKED_QTY
	, INSPECTED_QTY
	, ORDER_TYPE
	, STATUS
	, DOMAIN_ID
	, CREATOR_ID
	, UPDATER_ID
	, CREATED_AT
	, UPDATED_AT
) SELECT
	uuid_generate_v4()
	, BATCH_ID
	, JOB_DATE
	, JOB_SEQ
	, JOB_TYPE
	, STAGE_CD
	, COM_CD
	, EQUIP_GROUP_CD
	, EQUIP_TYPE
	, COALESCE(EQUIP_CD, :equipCd)
	, SHOP_CD
	, SHOP_NM
	, ORDERER_ID
	, ORDERER_NM
	, CLASS_CD
	, SKU_CD
	, MAX(SKU_NM)
	, MAX(SKU_BARCD)
	, MAX(BOX_IN_QTY)
	, 0
	, BOX_TYPE_CD
	, MAX(CUST_ORDER_NO)
	, ORDER_NO
	, INVOICE_ID
	, SUM(ORDER_QTY) AS ORDER_QTY
	, 0
	, 0
	, 0
	, ORDER_TYPE
	, 'W'
	, DOMAIN_ID
	, 'system'
	, 'system'
	, now()
	, now()
FROM
	ORDERS
WHERE
	DOMAIN_ID = :domainId
	AND BATCH_ID in (
		SELECT
			ID
		FROM
			JOB_BATCHES
		WHERE
			DOMAIN_ID = :domainId
			#if($batchId)
			AND ID = :batchId
			#end
			#if($batchGroupId)
			AND BATCH_GROUP_ID = :batchGroupId
			#end
	)
GROUP BY
	DOMAIN_ID, BATCH_ID, JOB_DATE, JOB_SEQ, JOB_TYPE,
	STAGE_CD, CLASS_CD, ORDER_NO, INVOICE_ID, ORDER_TYPE,
	COM_CD, SKU_CD, BOX_TYPE_CD, EQUIP_GROUP_CD, EQUIP_TYPE,
	EQUIP_CD, EQUIP_NM, SHOP_CD, SHOP_NM, ORDERER_ID, ORDERER_NM