SELECT WMS_BATCH_NO
     , WCS_BATCH_NO
     , COM_CD
     , AREA_CD
     , STAGE_CD
     , JOB_TYPE
     , EQUIP_TYPE
     , EQUIP_CD
     , COUNT(DISTINCT SKU_CD) AS TOTAL_ORDERS
     , SUM(ORDER_QTY) AS TOTAL_PCS
     , SUM(1) AS TOTAL_RECORDS
     , 'order' AS ITEM_TYPE
     , 'W' AS STATUS
     , 0 AS SKIP_FLAG
     , JOB_SEQ
  FROM WMS_IF_ORDERS 
 WHERE COM_CD = :comCd
   AND AREA_CD = :areaCd
   AND STAGE_CD = :stageCd
   AND JOB_DATE = :jobDate
   AND IF_FLAG = 'N'
 GROUP BY 
 	WMS_BATCH_NO, WCS_BATCH_NO, COM_CD, AREA_CD, STAGE_CD, JOB_DATE, JOB_TYPE, EQUIP_TYPE, EQUIP_CD, JOB_SEQ
 ORDER BY 
 	WMS_BATCH_NO, WCS_BATCH_NO,JOB_SEQ