SELECT 
	DOMAIN_ID,
	BATCH_ID,
	JOB_TYPE,
	COM_CD,
	:cellAssignType as CELL_ASSGN_TYPE,
	CLASS_CD AS CELL_ASSGN_CD,
	#if($cellAssignName)
	<_cellAssignName_> AS CELL_ASSGN_NM,
	#end
	EQUIP_TYPE,
	EQUIP_CD,
	EQUIP_NM,
	SUB_EQUIP_CD,
	BOX_CLASS_CD AS CLASS_CD,
	COUNT(DISTINCT(SKU_CD)) AS SKU_QTY,
	SUM(ORDER_QTY) AS TOTAL_PCS
FROM 
	ORDERS
WHERE 
	DOMAIN_ID = :domainId
	AND BATCH_ID = :batchId
GROUP BY 
	DOMAIN_ID,
	BATCH_ID,
	JOB_TYPE,
	COM_CD,
	CLASS_CD,
	#if($cellAssignName)
	<_cellAssignName_>,
	#end
	EQUIP_TYPE,
	EQUIP_CD,
	EQUIP_NM,
	SUB_EQUIP_CD,
	BOX_CLASS_CD
ORDER BY
	TOTAL_PCS DESC, SKU_QTY DESC