SELECT
	SHOP_QTY
	, TOTAL_ORDERS_PCS
	, ASSIGNED_CUST
	, ASSIGNED_PCS
	, SHOP_QTY - ASSIGNED_CUST REMAIN_CUST
	, TOTAL_ORDERS_PCS - ASSIGNED_PCS REMAIN_PCS
FROM
	(
		SELECT 
			COUNT(DISTINCT SKU_CD) AS SHOP_QTY
			, SUM(ORDER_QTY) AS TOTAL_ORDERS_PCS 
		FROM 
			ORDERS 
		WHERE 
			BATCH_ID = :batchId
	) ORDERS
,
	(
		SELECT 
			COUNT(DISTINCT CELL_ASSGN_CD) AS ASSIGNED_CUST
			, SUM(TOTAL_PCS) AS ASSIGNED_PCS 
		FROM 
			ORDER_PREPROCESSES 
		WHERE 
			BATCH_ID = :batchId
	) OP
