WITH V_JOB AS 
(
 SELECT SUB_EQUIP_CD AS CELL_CD, CLASS_CD, BOX_ID, COM_CD, SKU_CD
	  , PICKING_QTY AS PICK_QTY
	  , SUM(PICK_QTY) OVER (PARTITION BY DOMAIN_ID, BATCH_ID, CLASS_CD) AS ORDER_QTY
	  , SUM(PICKED_QTY) OVER (PARTITION BY DOMAIN_ID, BATCH_ID, CLASS_CD) AS PICKED_QTY
   FROM JOB_INSTANCES
  WHERE DOMAIN_ID = :domainId
	AND EQUIP_CD = :equipCd
	AND BATCH_ID = :batchId
	AND BOX_CLASS_CD = :cartJobId
),
V_JOB_STATUS AS 
(
 SELECT CELL_CD
	  , CASE WHEN MAX(ORDER_QTY) = MAX(PICKED_QTY) THEN true
		     ELSE false
	     END AS FINISHED
   FROM V_JOB
  GROUP BY CELL_CD
)
SELECT A.CELL_CD
     , B.CLASS_CD
	 , A.BOX_ID
	 , COALESCE(B.PICK_QTY, 0) AS PICK_QTY
	 , CASE WHEN A.ACTIVE_FLAG = true AND C.FINISHED IS NULL THEN false
	        ELSE A.ACTIVE_FLAG
	    END AS ACTIVE
	 , COALESCE(C.FINISHED, false) AS FINISHED
  FROM (
	   SELECT CELL_CD
            , CLASS_CD AS BOX_ID
            , ACTIVE_FLAG
 		    , 0 AS PICK_QTY
         FROM CELLS
	    WHERE DOMAIN_ID = :domainId
		  AND EQUIP_CD = :equipCd
       ) A
  LEFT OUTER JOIN
       (
	    SELECT CELL_CD, CLASS_CD, BOX_ID
	         , SUM(PICK_QTY) AS PICK_QTY
	      FROM V_JOB X
	     WHERE 1=1
		   #if($comCd)
		   AND COM_CD = :comCd
		   #end
		   #if($skuCd)
		   AND SKU_CD = :skuCd
		   #end
	     GROUP BY CELL_CD, CLASS_CD, BOX_ID
	   ) B
	ON A.CELL_CD = B.CELL_CD
  LEFT OUTER JOIN
       V_JOB_STATUS C
	ON A.CELL_CD = C.CELL_CD
 ORDER BY A.CELL_CD