SELECT
	B.BATCH_ID,
	B.INPUT_SEQ,
	B.EQUIP_TYPE,
	B.EQUIP_CD,
	B.ORDER_NO,
	B.BOX_ID,
	B.BOX_TYPE,
	B.SKU_QTY,
	B.PLAN_QTY,
	B.RESULT_QTY,
	CASE WHEN B.PLAN_QTY = B.RESULT_QTY THEN '1' ELSE '0' END AS STATUS,
	B.COLOR_CD
  FROM (
	SELECT
		A.BATCH_ID,
		MIN(A.INPUT_SEQ) AS INPUT_SEQ,
		A.EQUIP_TYPE,
		A.EQUIP_CD,
		A.ORDER_NO,
		A.BOX_ID,
		A.BOX_TYPE_CD AS BOX_TYPE,
		COUNT(1) AS SKU_QTY,
		SUM(A.PICK_QTY) AS PLAN_QTY,
		NVL(SUM(A.PICKED_QTY), 0) AS RESULT_QTY,
		MAX(A.COLOR_CD) AS COLOR_CD
	FROM (
		SELECT 
			BATCH_ID,
			ORDER_NO,
			MIN(INPUT_SEQ) AS INPUT_SEQ,
			EQUIP_TYPE,
			EQUIP_CD,
			BOX_ID,
			BOX_TYPE_CD,
			COM_CD,
			SKU_CD,
			SUM(PICK_QTY) AS PICK_QTY,
			NVL(SUM(PICKED_QTY),0) AS PICKED_QTY,
			MAX(COLOR_CD) AS COLOR_CD
		FROM
			JOB_INSTANCES
		WHERE
			DOMAIN_ID = :domainId
			AND BATCH_ID = :batchId
			AND EQUIP_TYPE = :equipType
			#if($equipCd)
			AND EQUIP_CD = :equipCd
			#end
			AND INPUT_SEQ >= 1
			AND STATUS  not in ('BW', 'W', 'A')
			AND ORDER_TYPE = 'MT'
		GROUP BY
			BATCH_ID, EQUIP_TYPE, EQUIP_CD, ORDER_NO, BOX_ID, BOX_TYPE_CD, COM_CD, SKU_CD) A
	GROUP BY
		BATCH_ID, EQUIP_TYPE, EQUIP_CD, ORDER_NO, BOX_ID, BOX_TYPE_CD
	) B
 ORDER BY
 	B.INPUT_SEQ DESC