-- TOTAL_ORDER_CNT : 총 주문 수 (출고 : 매장 수, 반품 : 상품 수), ASSIGNED_ORDER_CNT : 할당된 주문 수, REMAIN_ORDER_CNT : 남은 주문 수
-- TOTAL_CELL_CNT : 총 셀 수, ASSIGNED_CELL_CNT : 할당된 셀 수, REMAIN_CELL_CNT : 남은 셀 수
-- TOTAL_ORDER_PCS : 총 주문 PCS, ASSIGNED_ORDER_PCS : 할당된 주문 PCS, REMAIN_ORDER_PCS : 남은 주문 PCS

SELECT
	T.TOTAL_CELL_CNT,
	T.ASSIGNED_ORDER_CNT AS ASSIGNED_CELL_CNT,
	(T.TOTAL_CELL_CNT - T.ASSIGNED_ORDER_CNT) AS REMAIN_CELL_CNT,
	T.TOTAL_ORDER_CNT,
	T.ASSIGNED_ORDER_CNT,
	(T.TOTAL_ORDER_CNT - T.ASSIGNED_ORDER_CNT) AS REMAIN_ORDER_CNT,
	T.TOTAL_ORDER_PCS,
	T.ASSIGNED_ORDER_PCS,
	(T.TOTAL_ORDER_PCS - T.ASSIGNED_ORDER_PCS) AS REMAIN_ORDER_PCS
FROM ( 
	SELECT
		(SELECT COUNT(C.CELL_CD) AS TOTAL_CELL_CNT FROM CELLS C INNER JOIN RACKS R ON C.DOMAIN_ID = R.DOMAIN_ID AND C.EQUIP_CD = R.RACK_CD WHERE C.DOMAIN_ID = :domainId AND R.STAGE_CD = :stageCd AND (R.BATCH_ID IS NULL OR LENGTH(R.BATCH_ID) = 0)) AS TOTAL_CELL_CNT,
		A.TOTAL_ORDER_CNT,
		COALESCE(B.ASSIGNED_ORDER_CNT, 0) AS ASSIGNED_ORDER_CNT,
		A.TOTAL_ORDER_PCS,
		COALESCE(B.ASSIGNED_ORDER_PCS, 0) AS ASSIGNED_ORDER_PCS
	FROM (SELECT
   			BATCH_ID,
			COUNT(CELL_ASSGN_CD) AS TOTAL_ORDER_CNT,
			SUM(TOTAL_PCS)       AS TOTAL_ORDER_PCS
		FROM
			ORDER_PREPROCESSES
		WHERE
			DOMAIN_ID = :domainId AND BATCH_ID = :batchId
		GROUP BY 
			BATCH_ID
		) A
           
		LEFT OUTER JOIN
                   
		(SELECT
			I.BATCH_ID,
			SUM(I.ASSIGNED_ORDER_CNT) AS ASSIGNED_ORDER_CNT,
			SUM(I.ASSIGNED_ORDER_PCS / I.ORDER_CNT) AS ASSIGNED_ORDER_PCS
		FROM (SELECT
				BATCH_ID,
				COUNT(1)       AS ORDER_CNT ,
                1              AS ASSIGNED_ORDER_CNT,
                SUM(TOTAL_PCS) AS ASSIGNED_ORDER_PCS
			FROM
				ORDER_PREPROCESSES
			WHERE
				DOMAIN_ID = :domainId
				AND BATCH_ID = :batchId
				AND (EQUIP_CD IS NOT NULL AND LENGTH(EQUIP_CD) > 0)
			GROUP BY 
				BATCH_ID, CELL_ASSGN_CD
			) I
		GROUP BY 
			I.BATCH_ID) B
	
	ON A.BATCH_ID = B.BATCH_ID
) T