SELECT    
	A.RACK_CD,
	A.RACK_NM,
	A.TOTAL_CELLS - COALESCE(B.ASSIGNED_CELLS, 0) AS REMAIN_CELLS,
	COALESCE(B.ASSIGNED_CELLS, 0) AS ASSIGNED_CELLS,
	COALESCE(B.ASSIGNED_PCS, 0)   AS ASSIGNED_PCS
	
FROM (
	SELECT 
		R.RACK_CD,
		R.RACK_NM,
		COUNT(C.CELL_CD) AS TOTAL_CELLS
	FROM     
		CELLS C INNER JOIN RACKS R ON C.DOMAIN_ID = R.DOMAIN_ID AND C.EQUIP_CD = R.RACK_CD
	WHERE
		C.DOMAIN_ID = :domainId
		AND R.STAGE_CD = :stageCd
		AND R.JOB_TYPE = :jobType
		AND (R.BATCH_ID IS NULL OR LENGTH(R.BATCH_ID) = 0)
		AND C.ACTIVE_FLAG = :activeFlag
		#if($equipCds)
		AND R.RACK_CD IN (:equipCds)  
		#end
	GROUP BY 
		R.RACK_CD, R.RACK_NM
	) A

	LEFT OUTER JOIN
        
	(SELECT
		EQUIP_CD,
		COUNT(DISTINCT(CELL_ASSGN_CD)) 	AS ASSIGNED_CELLS,
		SUM(TOTAL_PCS)          		AS ASSIGNED_PCS
	FROM
		ORDER_PREPROCESSES
	WHERE
		DOMAIN_ID = :domainId
		AND BATCH_ID = :batchId
	GROUP BY
		EQUIP_CD) B

	ON A.RACK_CD = B.EQUIP_CD

ORDER BY A.RACK_CD