//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.09 at 08:21:26 오후 KST 
//


package operato.logis.couriers.service.cj.addr.soap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressSearchResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressSearchResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="boxTyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bscFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clntMgmCustCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clntNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cntrLarcCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dealFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvClsfCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvClsfNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrBranCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrBranNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrBranShortNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrEmpNickNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrEmpNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrEmpNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvSubClsfCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fareDiv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ferryFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthClsfCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthClsfNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthPreArrBranCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthPreArrBranNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthPreArrBranShortNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthPreArrEmpNickNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthPreArrEmpNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthPreArrEmpNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gthSubClsfCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jejuFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prngDivCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrClsfAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrEtcAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrNewAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrNewAddrDtl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrNewAddrYn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrOldAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrOldAddrDtl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrShortAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrZipnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprClsfAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprEtcAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprNewAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprNewAddrDtl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprNewAddrYn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprOldAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprOldAddrDtl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprShortAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprZipnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprsnAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressSearchResponse", propOrder = {
    "boxTyp",
    "bscFare",
    "clntMgmCustCd",
    "clntNum",
    "cntrLarcCd",
    "dealFare",
    "dlvClsfCd",
    "dlvClsfNm",
    "dlvPreArrBranCd",
    "dlvPreArrBranNm",
    "dlvPreArrBranShortNm",
    "dlvPreArrEmpNickNm",
    "dlvPreArrEmpNm",
    "dlvPreArrEmpNum",
    "dlvSubClsfCd",
    "errorCd",
    "errorMsg",
    "fareDiv",
    "ferryFare",
    "gthClsfCd",
    "gthClsfNm",
    "gthPreArrBranCd",
    "gthPreArrBranNm",
    "gthPreArrBranShortNm",
    "gthPreArrEmpNickNm",
    "gthPreArrEmpNm",
    "gthPreArrEmpNum",
    "gthSubClsfCd",
    "jejuFare",
    "orderNo",
    "prngDivCd",
    "rcvrAddr",
    "rcvrClsfAddr",
    "rcvrEtcAddr",
    "rcvrNewAddr",
    "rcvrNewAddrDtl",
    "rcvrNewAddrYn",
    "rcvrOldAddr",
    "rcvrOldAddrDtl",
    "rcvrShortAddr",
    "rcvrZipnum",
    "sndprClsfAddr",
    "sndprEtcAddr",
    "sndprNewAddr",
    "sndprNewAddrDtl",
    "sndprNewAddrYn",
    "sndprOldAddr",
    "sndprOldAddrDtl",
    "sndprShortAddr",
    "sndprZipnum",
    "sndprsnAddr"
})
public class AddressSearchResponse {

    protected String boxTyp;
    protected String bscFare;
    protected String clntMgmCustCd;
    protected String clntNum;
    protected String cntrLarcCd;
    protected String dealFare;
    protected String dlvClsfCd;
    protected String dlvClsfNm;
    protected String dlvPreArrBranCd;
    protected String dlvPreArrBranNm;
    protected String dlvPreArrBranShortNm;
    protected String dlvPreArrEmpNickNm;
    protected String dlvPreArrEmpNm;
    protected String dlvPreArrEmpNum;
    protected String dlvSubClsfCd;
    protected String errorCd;
    protected String errorMsg;
    protected String fareDiv;
    protected String ferryFare;
    protected String gthClsfCd;
    protected String gthClsfNm;
    protected String gthPreArrBranCd;
    protected String gthPreArrBranNm;
    protected String gthPreArrBranShortNm;
    protected String gthPreArrEmpNickNm;
    protected String gthPreArrEmpNm;
    protected String gthPreArrEmpNum;
    protected String gthSubClsfCd;
    protected String jejuFare;
    protected String orderNo;
    protected String prngDivCd;
    protected String rcvrAddr;
    protected String rcvrClsfAddr;
    protected String rcvrEtcAddr;
    protected String rcvrNewAddr;
    protected String rcvrNewAddrDtl;
    protected String rcvrNewAddrYn;
    protected String rcvrOldAddr;
    protected String rcvrOldAddrDtl;
    protected String rcvrShortAddr;
    protected String rcvrZipnum;
    protected String sndprClsfAddr;
    protected String sndprEtcAddr;
    protected String sndprNewAddr;
    protected String sndprNewAddrDtl;
    protected String sndprNewAddrYn;
    protected String sndprOldAddr;
    protected String sndprOldAddrDtl;
    protected String sndprShortAddr;
    protected String sndprZipnum;
    protected String sndprsnAddr;

    /**
     * Gets the value of the boxTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoxTyp() {
        return boxTyp;
    }

    /**
     * Sets the value of the boxTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoxTyp(String value) {
        this.boxTyp = value;
    }

    /**
     * Gets the value of the bscFare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBscFare() {
        return bscFare;
    }

    /**
     * Sets the value of the bscFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBscFare(String value) {
        this.bscFare = value;
    }

    /**
     * Gets the value of the clntMgmCustCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntMgmCustCd() {
        return clntMgmCustCd;
    }

    /**
     * Sets the value of the clntMgmCustCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntMgmCustCd(String value) {
        this.clntMgmCustCd = value;
    }

    /**
     * Gets the value of the clntNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntNum() {
        return clntNum;
    }

    /**
     * Sets the value of the clntNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntNum(String value) {
        this.clntNum = value;
    }

    /**
     * Gets the value of the cntrLarcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntrLarcCd() {
        return cntrLarcCd;
    }

    /**
     * Sets the value of the cntrLarcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntrLarcCd(String value) {
        this.cntrLarcCd = value;
    }

    /**
     * Gets the value of the dealFare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealFare() {
        return dealFare;
    }

    /**
     * Sets the value of the dealFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealFare(String value) {
        this.dealFare = value;
    }

    /**
     * Gets the value of the dlvClsfCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvClsfCd() {
        return dlvClsfCd;
    }

    /**
     * Sets the value of the dlvClsfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvClsfCd(String value) {
        this.dlvClsfCd = value;
    }

    /**
     * Gets the value of the dlvClsfNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvClsfNm() {
        return dlvClsfNm;
    }

    /**
     * Sets the value of the dlvClsfNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvClsfNm(String value) {
        this.dlvClsfNm = value;
    }

    /**
     * Gets the value of the dlvPreArrBranCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrBranCd() {
        return dlvPreArrBranCd;
    }

    /**
     * Sets the value of the dlvPreArrBranCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrBranCd(String value) {
        this.dlvPreArrBranCd = value;
    }

    /**
     * Gets the value of the dlvPreArrBranNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrBranNm() {
        return dlvPreArrBranNm;
    }

    /**
     * Sets the value of the dlvPreArrBranNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrBranNm(String value) {
        this.dlvPreArrBranNm = value;
    }

    /**
     * Gets the value of the dlvPreArrBranShortNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrBranShortNm() {
        return dlvPreArrBranShortNm;
    }

    /**
     * Sets the value of the dlvPreArrBranShortNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrBranShortNm(String value) {
        this.dlvPreArrBranShortNm = value;
    }

    /**
     * Gets the value of the dlvPreArrEmpNickNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrEmpNickNm() {
        return dlvPreArrEmpNickNm;
    }

    /**
     * Sets the value of the dlvPreArrEmpNickNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrEmpNickNm(String value) {
        this.dlvPreArrEmpNickNm = value;
    }

    /**
     * Gets the value of the dlvPreArrEmpNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrEmpNm() {
        return dlvPreArrEmpNm;
    }

    /**
     * Sets the value of the dlvPreArrEmpNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrEmpNm(String value) {
        this.dlvPreArrEmpNm = value;
    }

    /**
     * Gets the value of the dlvPreArrEmpNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrEmpNum() {
        return dlvPreArrEmpNum;
    }

    /**
     * Sets the value of the dlvPreArrEmpNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrEmpNum(String value) {
        this.dlvPreArrEmpNum = value;
    }

    /**
     * Gets the value of the dlvSubClsfCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvSubClsfCd() {
        return dlvSubClsfCd;
    }

    /**
     * Sets the value of the dlvSubClsfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvSubClsfCd(String value) {
        this.dlvSubClsfCd = value;
    }

    /**
     * Gets the value of the errorCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCd() {
        return errorCd;
    }

    /**
     * Sets the value of the errorCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCd(String value) {
        this.errorCd = value;
    }

    /**
     * Gets the value of the errorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * Sets the value of the errorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMsg(String value) {
        this.errorMsg = value;
    }

    /**
     * Gets the value of the fareDiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareDiv() {
        return fareDiv;
    }

    /**
     * Sets the value of the fareDiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareDiv(String value) {
        this.fareDiv = value;
    }

    /**
     * Gets the value of the ferryFare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFerryFare() {
        return ferryFare;
    }

    /**
     * Sets the value of the ferryFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFerryFare(String value) {
        this.ferryFare = value;
    }

    /**
     * Gets the value of the gthClsfCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthClsfCd() {
        return gthClsfCd;
    }

    /**
     * Sets the value of the gthClsfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthClsfCd(String value) {
        this.gthClsfCd = value;
    }

    /**
     * Gets the value of the gthClsfNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthClsfNm() {
        return gthClsfNm;
    }

    /**
     * Sets the value of the gthClsfNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthClsfNm(String value) {
        this.gthClsfNm = value;
    }

    /**
     * Gets the value of the gthPreArrBranCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthPreArrBranCd() {
        return gthPreArrBranCd;
    }

    /**
     * Sets the value of the gthPreArrBranCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthPreArrBranCd(String value) {
        this.gthPreArrBranCd = value;
    }

    /**
     * Gets the value of the gthPreArrBranNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthPreArrBranNm() {
        return gthPreArrBranNm;
    }

    /**
     * Sets the value of the gthPreArrBranNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthPreArrBranNm(String value) {
        this.gthPreArrBranNm = value;
    }

    /**
     * Gets the value of the gthPreArrBranShortNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthPreArrBranShortNm() {
        return gthPreArrBranShortNm;
    }

    /**
     * Sets the value of the gthPreArrBranShortNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthPreArrBranShortNm(String value) {
        this.gthPreArrBranShortNm = value;
    }

    /**
     * Gets the value of the gthPreArrEmpNickNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthPreArrEmpNickNm() {
        return gthPreArrEmpNickNm;
    }

    /**
     * Sets the value of the gthPreArrEmpNickNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthPreArrEmpNickNm(String value) {
        this.gthPreArrEmpNickNm = value;
    }

    /**
     * Gets the value of the gthPreArrEmpNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthPreArrEmpNm() {
        return gthPreArrEmpNm;
    }

    /**
     * Sets the value of the gthPreArrEmpNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthPreArrEmpNm(String value) {
        this.gthPreArrEmpNm = value;
    }

    /**
     * Gets the value of the gthPreArrEmpNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthPreArrEmpNum() {
        return gthPreArrEmpNum;
    }

    /**
     * Sets the value of the gthPreArrEmpNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthPreArrEmpNum(String value) {
        this.gthPreArrEmpNum = value;
    }

    /**
     * Gets the value of the gthSubClsfCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGthSubClsfCd() {
        return gthSubClsfCd;
    }

    /**
     * Sets the value of the gthSubClsfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGthSubClsfCd(String value) {
        this.gthSubClsfCd = value;
    }

    /**
     * Gets the value of the jejuFare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJejuFare() {
        return jejuFare;
    }

    /**
     * Sets the value of the jejuFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJejuFare(String value) {
        this.jejuFare = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the prngDivCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrngDivCd() {
        return prngDivCd;
    }

    /**
     * Sets the value of the prngDivCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrngDivCd(String value) {
        this.prngDivCd = value;
    }

    /**
     * Gets the value of the rcvrAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrAddr() {
        return rcvrAddr;
    }

    /**
     * Sets the value of the rcvrAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrAddr(String value) {
        this.rcvrAddr = value;
    }

    /**
     * Gets the value of the rcvrClsfAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrClsfAddr() {
        return rcvrClsfAddr;
    }

    /**
     * Sets the value of the rcvrClsfAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrClsfAddr(String value) {
        this.rcvrClsfAddr = value;
    }

    /**
     * Gets the value of the rcvrEtcAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrEtcAddr() {
        return rcvrEtcAddr;
    }

    /**
     * Sets the value of the rcvrEtcAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrEtcAddr(String value) {
        this.rcvrEtcAddr = value;
    }

    /**
     * Gets the value of the rcvrNewAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrNewAddr() {
        return rcvrNewAddr;
    }

    /**
     * Sets the value of the rcvrNewAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrNewAddr(String value) {
        this.rcvrNewAddr = value;
    }

    /**
     * Gets the value of the rcvrNewAddrDtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrNewAddrDtl() {
        return rcvrNewAddrDtl;
    }

    /**
     * Sets the value of the rcvrNewAddrDtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrNewAddrDtl(String value) {
        this.rcvrNewAddrDtl = value;
    }

    /**
     * Gets the value of the rcvrNewAddrYn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrNewAddrYn() {
        return rcvrNewAddrYn;
    }

    /**
     * Sets the value of the rcvrNewAddrYn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrNewAddrYn(String value) {
        this.rcvrNewAddrYn = value;
    }

    /**
     * Gets the value of the rcvrOldAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrOldAddr() {
        return rcvrOldAddr;
    }

    /**
     * Sets the value of the rcvrOldAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrOldAddr(String value) {
        this.rcvrOldAddr = value;
    }

    /**
     * Gets the value of the rcvrOldAddrDtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrOldAddrDtl() {
        return rcvrOldAddrDtl;
    }

    /**
     * Sets the value of the rcvrOldAddrDtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrOldAddrDtl(String value) {
        this.rcvrOldAddrDtl = value;
    }

    /**
     * Gets the value of the rcvrShortAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrShortAddr() {
        return rcvrShortAddr;
    }

    /**
     * Sets the value of the rcvrShortAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrShortAddr(String value) {
        this.rcvrShortAddr = value;
    }

    /**
     * Gets the value of the rcvrZipnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrZipnum() {
        return rcvrZipnum;
    }

    /**
     * Sets the value of the rcvrZipnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrZipnum(String value) {
        this.rcvrZipnum = value;
    }

    /**
     * Gets the value of the sndprClsfAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprClsfAddr() {
        return sndprClsfAddr;
    }

    /**
     * Sets the value of the sndprClsfAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprClsfAddr(String value) {
        this.sndprClsfAddr = value;
    }

    /**
     * Gets the value of the sndprEtcAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprEtcAddr() {
        return sndprEtcAddr;
    }

    /**
     * Sets the value of the sndprEtcAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprEtcAddr(String value) {
        this.sndprEtcAddr = value;
    }

    /**
     * Gets the value of the sndprNewAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprNewAddr() {
        return sndprNewAddr;
    }

    /**
     * Sets the value of the sndprNewAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprNewAddr(String value) {
        this.sndprNewAddr = value;
    }

    /**
     * Gets the value of the sndprNewAddrDtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprNewAddrDtl() {
        return sndprNewAddrDtl;
    }

    /**
     * Sets the value of the sndprNewAddrDtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprNewAddrDtl(String value) {
        this.sndprNewAddrDtl = value;
    }

    /**
     * Gets the value of the sndprNewAddrYn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprNewAddrYn() {
        return sndprNewAddrYn;
    }

    /**
     * Sets the value of the sndprNewAddrYn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprNewAddrYn(String value) {
        this.sndprNewAddrYn = value;
    }

    /**
     * Gets the value of the sndprOldAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprOldAddr() {
        return sndprOldAddr;
    }

    /**
     * Sets the value of the sndprOldAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprOldAddr(String value) {
        this.sndprOldAddr = value;
    }

    /**
     * Gets the value of the sndprOldAddrDtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprOldAddrDtl() {
        return sndprOldAddrDtl;
    }

    /**
     * Sets the value of the sndprOldAddrDtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprOldAddrDtl(String value) {
        this.sndprOldAddrDtl = value;
    }

    /**
     * Gets the value of the sndprShortAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprShortAddr() {
        return sndprShortAddr;
    }

    /**
     * Sets the value of the sndprShortAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprShortAddr(String value) {
        this.sndprShortAddr = value;
    }

    /**
     * Gets the value of the sndprZipnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprZipnum() {
        return sndprZipnum;
    }

    /**
     * Sets the value of the sndprZipnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprZipnum(String value) {
        this.sndprZipnum = value;
    }

    /**
     * Gets the value of the sndprsnAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprsnAddr() {
        return sndprsnAddr;
    }

    /**
     * Sets the value of the sndprsnAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprsnAddr(String value) {
        this.sndprsnAddr = value;
    }

}
