//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.09 at 08:21:26 오후 KST 
//


package operato.logis.couriers.service.cj.addr.soap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressSearchResponse2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressSearchResponse2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cgosts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clntMgmCustCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clntNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvClsfCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvClsfNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrBranCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrBranNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrBranShortNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrEmpNickNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrEmpNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvPreArrEmpNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvSubClsfCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prngDivCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrClsfAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrEtcAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrNewAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrNewAddrDtl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrNewAddrYn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrOldAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrOldAddrDtl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrShortAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrZipnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rspsDiv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="zpid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressSearchResponse2", propOrder = {
    "cgosts",
    "clntMgmCustCd",
    "clntNum",
    "dlvClsfCd",
    "dlvClsfNm",
    "dlvPreArrBranCd",
    "dlvPreArrBranNm",
    "dlvPreArrBranShortNm",
    "dlvPreArrEmpNickNm",
    "dlvPreArrEmpNm",
    "dlvPreArrEmpNum",
    "dlvSubClsfCd",
    "errorCd",
    "errorMsg",
    "prngDivCd",
    "rcvrClsfAddr",
    "rcvrEtcAddr",
    "rcvrNewAddr",
    "rcvrNewAddrDtl",
    "rcvrNewAddrYn",
    "rcvrOldAddr",
    "rcvrOldAddrDtl",
    "rcvrShortAddr",
    "rcvrZipnum",
    "rspsDiv",
    "zpid"
})
public class AddressSearchResponse2 {

    protected String cgosts;
    protected String clntMgmCustCd;
    protected String clntNum;
    protected String dlvClsfCd;
    protected String dlvClsfNm;
    protected String dlvPreArrBranCd;
    protected String dlvPreArrBranNm;
    protected String dlvPreArrBranShortNm;
    protected String dlvPreArrEmpNickNm;
    protected String dlvPreArrEmpNm;
    protected String dlvPreArrEmpNum;
    protected String dlvSubClsfCd;
    protected String errorCd;
    protected String errorMsg;
    protected String prngDivCd;
    protected String rcvrClsfAddr;
    protected String rcvrEtcAddr;
    protected String rcvrNewAddr;
    protected String rcvrNewAddrDtl;
    protected String rcvrNewAddrYn;
    protected String rcvrOldAddr;
    protected String rcvrOldAddrDtl;
    protected String rcvrShortAddr;
    protected String rcvrZipnum;
    protected String rspsDiv;
    protected int zpid;

    /**
     * Gets the value of the cgosts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCgosts() {
        return cgosts;
    }

    /**
     * Sets the value of the cgosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCgosts(String value) {
        this.cgosts = value;
    }

    /**
     * Gets the value of the clntMgmCustCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntMgmCustCd() {
        return clntMgmCustCd;
    }

    /**
     * Sets the value of the clntMgmCustCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntMgmCustCd(String value) {
        this.clntMgmCustCd = value;
    }

    /**
     * Gets the value of the clntNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntNum() {
        return clntNum;
    }

    /**
     * Sets the value of the clntNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntNum(String value) {
        this.clntNum = value;
    }

    /**
     * Gets the value of the dlvClsfCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvClsfCd() {
        return dlvClsfCd;
    }

    /**
     * Sets the value of the dlvClsfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvClsfCd(String value) {
        this.dlvClsfCd = value;
    }

    /**
     * Gets the value of the dlvClsfNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvClsfNm() {
        return dlvClsfNm;
    }

    /**
     * Sets the value of the dlvClsfNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvClsfNm(String value) {
        this.dlvClsfNm = value;
    }

    /**
     * Gets the value of the dlvPreArrBranCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrBranCd() {
        return dlvPreArrBranCd;
    }

    /**
     * Sets the value of the dlvPreArrBranCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrBranCd(String value) {
        this.dlvPreArrBranCd = value;
    }

    /**
     * Gets the value of the dlvPreArrBranNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrBranNm() {
        return dlvPreArrBranNm;
    }

    /**
     * Sets the value of the dlvPreArrBranNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrBranNm(String value) {
        this.dlvPreArrBranNm = value;
    }

    /**
     * Gets the value of the dlvPreArrBranShortNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrBranShortNm() {
        return dlvPreArrBranShortNm;
    }

    /**
     * Sets the value of the dlvPreArrBranShortNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrBranShortNm(String value) {
        this.dlvPreArrBranShortNm = value;
    }

    /**
     * Gets the value of the dlvPreArrEmpNickNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrEmpNickNm() {
        return dlvPreArrEmpNickNm;
    }

    /**
     * Sets the value of the dlvPreArrEmpNickNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrEmpNickNm(String value) {
        this.dlvPreArrEmpNickNm = value;
    }

    /**
     * Gets the value of the dlvPreArrEmpNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrEmpNm() {
        return dlvPreArrEmpNm;
    }

    /**
     * Sets the value of the dlvPreArrEmpNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrEmpNm(String value) {
        this.dlvPreArrEmpNm = value;
    }

    /**
     * Gets the value of the dlvPreArrEmpNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvPreArrEmpNum() {
        return dlvPreArrEmpNum;
    }

    /**
     * Sets the value of the dlvPreArrEmpNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvPreArrEmpNum(String value) {
        this.dlvPreArrEmpNum = value;
    }

    /**
     * Gets the value of the dlvSubClsfCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvSubClsfCd() {
        return dlvSubClsfCd;
    }

    /**
     * Sets the value of the dlvSubClsfCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvSubClsfCd(String value) {
        this.dlvSubClsfCd = value;
    }

    /**
     * Gets the value of the errorCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCd() {
        return errorCd;
    }

    /**
     * Sets the value of the errorCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCd(String value) {
        this.errorCd = value;
    }

    /**
     * Gets the value of the errorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * Sets the value of the errorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMsg(String value) {
        this.errorMsg = value;
    }

    /**
     * Gets the value of the prngDivCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrngDivCd() {
        return prngDivCd;
    }

    /**
     * Sets the value of the prngDivCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrngDivCd(String value) {
        this.prngDivCd = value;
    }

    /**
     * Gets the value of the rcvrClsfAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrClsfAddr() {
        return rcvrClsfAddr;
    }

    /**
     * Sets the value of the rcvrClsfAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrClsfAddr(String value) {
        this.rcvrClsfAddr = value;
    }

    /**
     * Gets the value of the rcvrEtcAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrEtcAddr() {
        return rcvrEtcAddr;
    }

    /**
     * Sets the value of the rcvrEtcAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrEtcAddr(String value) {
        this.rcvrEtcAddr = value;
    }

    /**
     * Gets the value of the rcvrNewAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrNewAddr() {
        return rcvrNewAddr;
    }

    /**
     * Sets the value of the rcvrNewAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrNewAddr(String value) {
        this.rcvrNewAddr = value;
    }

    /**
     * Gets the value of the rcvrNewAddrDtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrNewAddrDtl() {
        return rcvrNewAddrDtl;
    }

    /**
     * Sets the value of the rcvrNewAddrDtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrNewAddrDtl(String value) {
        this.rcvrNewAddrDtl = value;
    }

    /**
     * Gets the value of the rcvrNewAddrYn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrNewAddrYn() {
        return rcvrNewAddrYn;
    }

    /**
     * Sets the value of the rcvrNewAddrYn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrNewAddrYn(String value) {
        this.rcvrNewAddrYn = value;
    }

    /**
     * Gets the value of the rcvrOldAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrOldAddr() {
        return rcvrOldAddr;
    }

    /**
     * Sets the value of the rcvrOldAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrOldAddr(String value) {
        this.rcvrOldAddr = value;
    }

    /**
     * Gets the value of the rcvrOldAddrDtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrOldAddrDtl() {
        return rcvrOldAddrDtl;
    }

    /**
     * Sets the value of the rcvrOldAddrDtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrOldAddrDtl(String value) {
        this.rcvrOldAddrDtl = value;
    }

    /**
     * Gets the value of the rcvrShortAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrShortAddr() {
        return rcvrShortAddr;
    }

    /**
     * Sets the value of the rcvrShortAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrShortAddr(String value) {
        this.rcvrShortAddr = value;
    }

    /**
     * Gets the value of the rcvrZipnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrZipnum() {
        return rcvrZipnum;
    }

    /**
     * Sets the value of the rcvrZipnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrZipnum(String value) {
        this.rcvrZipnum = value;
    }

    /**
     * Gets the value of the rspsDiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRspsDiv() {
        return rspsDiv;
    }

    /**
     * Sets the value of the rspsDiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRspsDiv(String value) {
        this.rspsDiv = value;
    }

    /**
     * Gets the value of the zpid property.
     * 
     */
    public int getZpid() {
        return zpid;
    }

    /**
     * Sets the value of the zpid property.
     * 
     */
    public void setZpid(int value) {
        this.zpid = value;
    }

}
