//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.09 at 08:21:26 오후 KST 
//


package operato.logis.couriers.service.cj.addr.soap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressSearchRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressSearchRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="boxTyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clntMgmCustCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clntNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cntrLarcCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fareDiv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prngDivCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sndprsnAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressSearchRequest", propOrder = {
    "boxTyp",
    "clntMgmCustCd",
    "clntNum",
    "cntrLarcCd",
    "fareDiv",
    "orderNo",
    "prngDivCd",
    "rcvrAddr",
    "sndprsnAddr"
})
public class AddressSearchRequest {

    protected String boxTyp;
    protected String clntMgmCustCd;
    protected String clntNum;
    protected String cntrLarcCd;
    protected String fareDiv;
    protected String orderNo;
    protected String prngDivCd;
    protected String rcvrAddr;
    protected String sndprsnAddr;

    /**
     * Gets the value of the boxTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoxTyp() {
        return boxTyp;
    }

    /**
     * Sets the value of the boxTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoxTyp(String value) {
        this.boxTyp = value;
    }

    /**
     * Gets the value of the clntMgmCustCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntMgmCustCd() {
        return clntMgmCustCd;
    }

    /**
     * Sets the value of the clntMgmCustCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntMgmCustCd(String value) {
        this.clntMgmCustCd = value;
    }

    /**
     * Gets the value of the clntNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntNum() {
        return clntNum;
    }

    /**
     * Sets the value of the clntNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntNum(String value) {
        this.clntNum = value;
    }

    /**
     * Gets the value of the cntrLarcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntrLarcCd() {
        return cntrLarcCd;
    }

    /**
     * Sets the value of the cntrLarcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntrLarcCd(String value) {
        this.cntrLarcCd = value;
    }

    /**
     * Gets the value of the fareDiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareDiv() {
        return fareDiv;
    }

    /**
     * Sets the value of the fareDiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareDiv(String value) {
        this.fareDiv = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the prngDivCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrngDivCd() {
        return prngDivCd;
    }

    /**
     * Sets the value of the prngDivCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrngDivCd(String value) {
        this.prngDivCd = value;
    }

    /**
     * Gets the value of the rcvrAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrAddr() {
        return rcvrAddr;
    }

    /**
     * Sets the value of the rcvrAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrAddr(String value) {
        this.rcvrAddr = value;
    }

    /**
     * Gets the value of the sndprsnAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndprsnAddr() {
        return sndprsnAddr;
    }

    /**
     * Sets the value of the sndprsnAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndprsnAddr(String value) {
        this.sndprsnAddr = value;
    }

}
