//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.09 at 08:21:26 오후 KST 
//


package operato.logis.couriers.service.cj.addr.soap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressSearchRequestHsp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressSearchRequestHsp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cgosts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clntMgmCustCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clntNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dlvstGbcd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prngDivCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rcvrAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressSearchRequestHsp", propOrder = {
    "cgosts",
    "clntMgmCustCd",
    "clntNum",
    "dlvstGbcd",
    "prngDivCd",
    "rcvrAddr"
})
public class AddressSearchRequestHsp {

    protected String cgosts;
    protected String clntMgmCustCd;
    protected String clntNum;
    protected String dlvstGbcd;
    protected String prngDivCd;
    protected String rcvrAddr;

    /**
     * Gets the value of the cgosts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCgosts() {
        return cgosts;
    }

    /**
     * Sets the value of the cgosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCgosts(String value) {
        this.cgosts = value;
    }

    /**
     * Gets the value of the clntMgmCustCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntMgmCustCd() {
        return clntMgmCustCd;
    }

    /**
     * Sets the value of the clntMgmCustCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntMgmCustCd(String value) {
        this.clntMgmCustCd = value;
    }

    /**
     * Gets the value of the clntNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntNum() {
        return clntNum;
    }

    /**
     * Sets the value of the clntNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntNum(String value) {
        this.clntNum = value;
    }

    /**
     * Gets the value of the dlvstGbcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvstGbcd() {
        return dlvstGbcd;
    }

    /**
     * Sets the value of the dlvstGbcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvstGbcd(String value) {
        this.dlvstGbcd = value;
    }

    /**
     * Gets the value of the prngDivCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrngDivCd() {
        return prngDivCd;
    }

    /**
     * Sets the value of the prngDivCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrngDivCd(String value) {
        this.prngDivCd = value;
    }

    /**
     * Gets the value of the rcvrAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrAddr() {
        return rcvrAddr;
    }

    /**
     * Sets the value of the rcvrAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrAddr(String value) {
        this.rcvrAddr = value;
    }

}
