//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.09 at 08:21:26 오후 KST 
//


package operato.logis.couriers.service.cj.addr.soap.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cj.mps.service.impl.soap.addr.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAddressInformationByValue3Response_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressInformationByValue3Response");
    private final static QName _GetAddressInformationByValue2Response_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressInformationByValue2Response");
    private final static QName _GetAddressByValueHspResponse_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressByValue_hspResponse");
    private final static QName _GetAddressByValueHsp_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressByValue_hsp");
    private final static QName _GetAddressInformationByValue2_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressInformationByValue2");
    private final static QName _GetAddressInformationResponse_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressInformationResponse");
    private final static QName _GetAddressInformationByValue3_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressInformationByValue3");
    private final static QName _GetAddressByValueRsps_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressByValue_rsps");
    private final static QName _GetAddressInformationByValueResponse_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressInformationByValueResponse");
    private final static QName _GetAddressInformation_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressInformation");
    private final static QName _GetAddressInformationByValue_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressInformationByValue");
    private final static QName _GetAddressByValueRspsResponse_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressByValue_rspsResponse");
    private final static QName _GetAddressByValuePost_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressByValue_post");
    private final static QName _GetAddressByValuePostResponse_QNAME = new QName("http://webservice.address.nplus.doortodoor.co.kr/", "getAddressByValue_postResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cj.mps.service.impl.soap.addr.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAddressByValueRspsResponse }
     * 
     */
    public GetAddressByValueRspsResponse createGetAddressByValueRspsResponse() {
        return new GetAddressByValueRspsResponse();
    }

    /**
     * Create an instance of {@link GetAddressInformationByValueResponse }
     * 
     */
    public GetAddressInformationByValueResponse createGetAddressInformationByValueResponse() {
        return new GetAddressInformationByValueResponse();
    }

    /**
     * Create an instance of {@link GetAddressInformationByValue2Response }
     * 
     */
    public GetAddressInformationByValue2Response createGetAddressInformationByValue2Response() {
        return new GetAddressInformationByValue2Response();
    }

    /**
     * Create an instance of {@link AddressSearchRequestHsp }
     * 
     */
    public AddressSearchRequestHsp createAddressSearchRequestHsp() {
        return new AddressSearchRequestHsp();
    }

    /**
     * Create an instance of {@link GetAddressInformationByValue2 }
     * 
     */
    public GetAddressInformationByValue2 createGetAddressInformationByValue2() {
        return new GetAddressInformationByValue2();
    }

    /**
     * Create an instance of {@link GetAddressByValuePost }
     * 
     */
    public GetAddressByValuePost createGetAddressByValuePost() {
        return new GetAddressByValuePost();
    }

    /**
     * Create an instance of {@link GetAddressInformation }
     * 
     */
    public GetAddressInformation createGetAddressInformation() {
        return new GetAddressInformation();
    }

    /**
     * Create an instance of {@link AddressSearchResponse }
     * 
     */
    public AddressSearchResponse createAddressSearchResponse() {
        return new AddressSearchResponse();
    }

    /**
     * Create an instance of {@link AddressSearchRequest }
     * 
     */
    public AddressSearchRequest createAddressSearchRequest() {
        return new AddressSearchRequest();
    }

    /**
     * Create an instance of {@link GetAddressByValueHsp }
     * 
     */
    public GetAddressByValueHsp createGetAddressByValueHsp() {
        return new GetAddressByValueHsp();
    }

    /**
     * Create an instance of {@link GetAddressInformationByValue3Response }
     * 
     */
    public GetAddressInformationByValue3Response createGetAddressInformationByValue3Response() {
        return new GetAddressInformationByValue3Response();
    }

    /**
     * Create an instance of {@link GetAddressByValueHspResponse }
     * 
     */
    public GetAddressByValueHspResponse createGetAddressByValueHspResponse() {
        return new GetAddressByValueHspResponse();
    }

    /**
     * Create an instance of {@link AddressSearchResponseEbay }
     * 
     */
    public AddressSearchResponseEbay createAddressSearchResponseEbay() {
        return new AddressSearchResponseEbay();
    }

    /**
     * Create an instance of {@link AddressSearchRequestEbay }
     * 
     */
    public AddressSearchRequestEbay createAddressSearchRequestEbay() {
        return new AddressSearchRequestEbay();
    }

    /**
     * Create an instance of {@link GetAddressInformationByValue3 }
     * 
     */
    public GetAddressInformationByValue3 createGetAddressInformationByValue3() {
        return new GetAddressInformationByValue3();
    }

    /**
     * Create an instance of {@link GetAddressInformationResponse }
     * 
     */
    public GetAddressInformationResponse createGetAddressInformationResponse() {
        return new GetAddressInformationResponse();
    }

    /**
     * Create an instance of {@link AddressSearchResponse2 }
     * 
     */
    public AddressSearchResponse2 createAddressSearchResponse2() {
        return new AddressSearchResponse2();
    }

    /**
     * Create an instance of {@link GetAddressByValuePostResponse }
     * 
     */
    public GetAddressByValuePostResponse createGetAddressByValuePostResponse() {
        return new GetAddressByValuePostResponse();
    }

    /**
     * Create an instance of {@link GetAddressInformationByValue }
     * 
     */
    public GetAddressInformationByValue createGetAddressInformationByValue() {
        return new GetAddressInformationByValue();
    }

    /**
     * Create an instance of {@link GetAddressByValueRsps }
     * 
     */
    public GetAddressByValueRsps createGetAddressByValueRsps() {
        return new GetAddressByValueRsps();
    }

    /**
     * Create an instance of {@link AddressSearchRequest2 }
     * 
     */
    public AddressSearchRequest2 createAddressSearchRequest2() {
        return new AddressSearchRequest2();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressInformationByValue3Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressInformationByValue3Response")
    public JAXBElement<GetAddressInformationByValue3Response> createGetAddressInformationByValue3Response(GetAddressInformationByValue3Response value) {
        return new JAXBElement<GetAddressInformationByValue3Response>(_GetAddressInformationByValue3Response_QNAME, GetAddressInformationByValue3Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressInformationByValue2Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressInformationByValue2Response")
    public JAXBElement<GetAddressInformationByValue2Response> createGetAddressInformationByValue2Response(GetAddressInformationByValue2Response value) {
        return new JAXBElement<GetAddressInformationByValue2Response>(_GetAddressInformationByValue2Response_QNAME, GetAddressInformationByValue2Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressByValueHspResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressByValue_hspResponse")
    public JAXBElement<GetAddressByValueHspResponse> createGetAddressByValueHspResponse(GetAddressByValueHspResponse value) {
        return new JAXBElement<GetAddressByValueHspResponse>(_GetAddressByValueHspResponse_QNAME, GetAddressByValueHspResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressByValueHsp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressByValue_hsp")
    public JAXBElement<GetAddressByValueHsp> createGetAddressByValueHsp(GetAddressByValueHsp value) {
        return new JAXBElement<GetAddressByValueHsp>(_GetAddressByValueHsp_QNAME, GetAddressByValueHsp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressInformationByValue2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressInformationByValue2")
    public JAXBElement<GetAddressInformationByValue2> createGetAddressInformationByValue2(GetAddressInformationByValue2 value) {
        return new JAXBElement<GetAddressInformationByValue2>(_GetAddressInformationByValue2_QNAME, GetAddressInformationByValue2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressInformationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressInformationResponse")
    public JAXBElement<GetAddressInformationResponse> createGetAddressInformationResponse(GetAddressInformationResponse value) {
        return new JAXBElement<GetAddressInformationResponse>(_GetAddressInformationResponse_QNAME, GetAddressInformationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressInformationByValue3 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressInformationByValue3")
    public JAXBElement<GetAddressInformationByValue3> createGetAddressInformationByValue3(GetAddressInformationByValue3 value) {
        return new JAXBElement<GetAddressInformationByValue3>(_GetAddressInformationByValue3_QNAME, GetAddressInformationByValue3 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressByValueRsps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressByValue_rsps")
    public JAXBElement<GetAddressByValueRsps> createGetAddressByValueRsps(GetAddressByValueRsps value) {
        return new JAXBElement<GetAddressByValueRsps>(_GetAddressByValueRsps_QNAME, GetAddressByValueRsps.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressInformationByValueResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressInformationByValueResponse")
    public JAXBElement<GetAddressInformationByValueResponse> createGetAddressInformationByValueResponse(GetAddressInformationByValueResponse value) {
        return new JAXBElement<GetAddressInformationByValueResponse>(_GetAddressInformationByValueResponse_QNAME, GetAddressInformationByValueResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressInformation")
    public JAXBElement<GetAddressInformation> createGetAddressInformation(GetAddressInformation value) {
        return new JAXBElement<GetAddressInformation>(_GetAddressInformation_QNAME, GetAddressInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressInformationByValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressInformationByValue")
    public JAXBElement<GetAddressInformationByValue> createGetAddressInformationByValue(GetAddressInformationByValue value) {
        return new JAXBElement<GetAddressInformationByValue>(_GetAddressInformationByValue_QNAME, GetAddressInformationByValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressByValueRspsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressByValue_rspsResponse")
    public JAXBElement<GetAddressByValueRspsResponse> createGetAddressByValueRspsResponse(GetAddressByValueRspsResponse value) {
        return new JAXBElement<GetAddressByValueRspsResponse>(_GetAddressByValueRspsResponse_QNAME, GetAddressByValueRspsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressByValuePost }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressByValue_post")
    public JAXBElement<GetAddressByValuePost> createGetAddressByValuePost(GetAddressByValuePost value) {
        return new JAXBElement<GetAddressByValuePost>(_GetAddressByValuePost_QNAME, GetAddressByValuePost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAddressByValuePostResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.address.nplus.doortodoor.co.kr/", name = "getAddressByValue_postResponse")
    public JAXBElement<GetAddressByValuePostResponse> createGetAddressByValuePostResponse(GetAddressByValuePostResponse value) {
        return new JAXBElement<GetAddressByValuePostResponse>(_GetAddressByValuePostResponse_QNAME, GetAddressByValuePostResponse.class, null, value);
    }

}
