//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.09 at 08:21:26 오후 KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservice.address.nplus.doortodoor.co.kr/")
package operato.logis.couriers.service.cj.addr.soap.wsdl;
