SELECT
	B.ACTUAL_ORDER,
	A.PICKED_QTY AS ACTUAL_PCS,
	((PICKED_QTY / PICK_QTY) * 100) AS PROGRESS_RATE,
	ROUND(PICKED_QTY / ROUND((PICK_ENDED_AT - PICK_STARTED_AT) * 24, 2), 2) AS JOB_UPH
FROM ( 
	(SELECT
		BATCH_ID,
		SUM(PICK_QTY) AS PICK_QTY,
		NVL(SUM(PICKED_QTY), 0) AS PICKED_QTY,
		TO_DATE(REPLACE(MIN(PICK_STARTED_AT), '-', ''), 'YYYYMMDD HH24:MI:SS') AS PICK_STARTED_AT,
		TO_DATE(REPLACE(MAX(PICK_ENDED_AT), '-', ''), 'YYYYMMDD HH24:MI:SS') AS PICK_ENDED_AT
	FROM    
		JOB_INSTANCES
	WHERE   
		DOMAIN_ID = :domainId
		AND BATCH_ID = :batchId
	GROUP BY
		BATCH_ID
	) A
	
	INNER JOIN
	
	(SELECT
		BATCH_ID,
		COUNT(DISTINCT (CLASS_CD)) ACTUAL_ORDER
	FROM    
		JOB_INSTANCES
	WHERE   
		DOMAIN_ID = :domainId
		AND BATCH_ID = :batchId
		AND PICK_ENDED_AT IS NOT NULL
		AND PICKED_QTY > 0
	GROUP BY
		BATCH_ID) B
		
	ON A.BATCH_ID = B.BATCH_ID
)